apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: maestro
  name: results-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 60Gi
  selector:
    matchLabels:
      app: maestro