apiVersion: apps/v1
kind: Deployment
metadata:
  name: maestro-results
spec:
  replicas: 1
  selector:
    matchLabels:
      component: results
      app: maestro
  template:
    metadata:
      labels:
        component: results
        app: maestro
    spec:
      strategy:
        type: Recreate
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              preference:
                matchExpressions:
                  - key: maestro-node-role
                    operator: In
                    values:
                      - infra
      containers:
        - name: maestro-reports
          image: maestroperf/maestro-results-server:edge
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /api/live
              port: 6500
            initialDelaySeconds: 5
            timeoutSeconds: 5
            periodSeconds: 20
            failureThreshold: 3
          env:
            - name: MAESTRO_BROKER
              value: mqtt://broker
            - name: MAESTRO_REPORTS_DRIVER
              value: org.mariadb.jdbc.Driver
# Change me
             - name: MAESTRO_REPORTS_DATASOURCE_URL
              value: jdbc:mariadb://my.database.host:3306/maestro
            - name: MAESTRO_REPORTS_DATASOURCE_USERNAME
              value: maestro
            - name: MAESTRO_REPORTS_DATASOURCE_PASSWORD
              value: maestro-dev
          ports:
            - name: http
              containerPort: 6500
          volumeMounts:
            - mountPath: /maestro
              name: results-data
      volumes:
        - name: results-data
          persistentVolumeClaim:
            claimName: results-data
